stages:
  - deploy

default:
  tags:
    - cloud-ru

deploy:
  stage: deploy
  script:
    - echo "Setting up environment files..."
    - echo -e "${backend_env}"  > ./backend/.env
    - echo -e "${frontend_env}" > ./frontend/.env

    - echo "Getting Commit SHA..."
    - export SHA_SHORT=$(git rev-parse --short HEAD)
    - echo "SHA_SHORT=${SHA_SHORT}" >> .gitlab-ci.env
    
    - echo "Setting Image Tag..."
    - export IMAGE_TAG="dev-${SHA_SHORT}"
    - echo "IMAGE_TAG=${IMAGE_TAG}" >> .gitlab-ci.env

    - echo "Stopping and removing old containers..."
    - docker compose -f docker-compose.prod.yml -p sposchedule down

    - echo "Rebuilding and starting containers..."
    - docker compose -f docker-compose.prod.yml -p sposchedule up -d --build

  only:
    - dev
