services:
  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: green
      POSTGRES_PASSWORD: 123123
      POSTGRES_DB: sposchedule
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
