version: '3.8'

services:
    # PHP Service
    app:
        build:
            context: .
            dockerfile: backend/Dockerfile
        image: php:8.3-fpm
        restart: unless-stopped
        tty: true
        environment:
            SERVICE_NAME: app
            SERVICE_TAGS: dev
        working_dir: /var/www/backend
        volumes:
            - ./backend:/var/www/backend
            - ./backend/storage:/var/www/backend/storage # Монтируем storage отдельно
        networks:
            - app-network

    # Node Service (запускается только при сборке фронтенда)
    node:
        build:
            context: .
            dockerfile: frontend/Dockerfile
        volumes:
            - ./frontend:/var/www/frontend # Монтируем только фронтенд
        networks:
            - app-network

    # Nginx Service
    webserver:
        image: nginx:latest
        restart: unless-stopped
        tty: true
        ports:
            - "82:80"
            - "445:443"
        volumes:
            - ./docker/nginx/conf.d:/etc/nginx/conf.d
            - ./backend/public:/var/www/backend/public # Монтируем только public директорию
            - ./frontend/dist:/var/www/frontend/dist # Монтируем dist для Vue
        networks:
            - app-network

    # PostgreSQL Service
    db:
        image: postgres:13.0
        restart: always
        ports:
            - 5434:5432
        env_file:
            - ./backend/.env
        environment:
            POSTGRES_PASSWORD: ${DB_PASSWORD}
            POSTGRES_USER: ${DB_USERNAME}
            POSTGRES_DB: sposchedule
        volumes:
            - db:/var/lib/postgresql/data
        networks:
            - app-network

# Docker Networks
networks:
    app-network:
        driver: bridge

# Docker Volumes
volumes:
    db:
