services:

    # Node Service (запускается только при сборке фронтенда)
    node:
        build:
            context: .
            dockerfile: ./frontend/Dockerfile
        image: sposchedule-frontend:${IMAGE_TAG}
        ports:
            - "8080:80"
        networks:
            - app-network

    # PHP Service
    php-fpm:
        build:
            context: .
            dockerfile: ./backend/Dockerfile
        image: sposchedule-backend:${IMAGE_TAG}
        restart: unless-stopped
        ports:
            - "82:80"
        working_dir: /var/www/backend
        depends_on:
            - db
        networks:
            - app-network

    # PostgreSQL Service
    db:
        image: postgres:13.0
        restart: always
        ports:
            - 5434:5432
        environment:
            POSTGRES_PASSWORD: ${DB_PASSWORD}
            POSTGRES_USER: ${DB_USERNAME}
            POSTGRES_DB: sposchedule
        volumes:
            - db:/var/lib/postgresql/data
        networks:
            - app-network

# Docker Networks
networks:
    app-network:
        driver: bridge

# Docker Volumes
volumes:
    db:
