name: Deploy Application to dev environment

on:
  push:
    branches:
      - dev

jobs:
  deploy:
    runs-on: linux
    steps:
      - name: Переходим в папку проекта и пересобираем
        run: |
          cd /home/green/sposchedule
          git pull origin dev
          docker compose -f docker-compose.prod.yml -p sposchedule up -d --build
