name: Deploy Application

on:
  push:

jobs:
  deploy:
    runs-on: linux
    steps:
      - name: Переходим в папку проекта и пересобираем
        run: |
          cd /home/green/sposchedule
          git pull
          docker compose -f docker-compose.prod.yml -p sposchedule up -d --build
